### ISSUE TITLE
Dependency on 'tiles' module

### ISSUE THREAD

**Issue by gratex** [vvoovv/djeo#5]
Is it expected that 'djeo' module is always used with 'tiles' module?

Because if not, dependency  "tiles/BaseTileable" in "djeo/djeo/WebTiles" causes error
in Dojo build.

	error(311) Missing dependency. module: djeo/djeo/WebTiles; dependency: tiles/BaseTileable

**Comment by vvoovv** [comment]
Package 'tiles' contains my own implementation of tiled bitmap maps. It's not that perfect as Leaflet of OpenLayers. You probably don't need it.
